// GENERATE ALL PSEUDO LEGAL MOVES, GENERATE ALL LEGAL MOVES, GENERATE ALL CAPTURES, GENERATE ALL CHECKS
// IS_LEGAL_MOVE, IS_PSEUDO_LEGAL_MOVE, IS_IN_CHECK (= GENERATE ALL CHECKS?)

// https://peterellisjones.com/posts/generating-legal-chess-moves-efficiently/